### ISSUE TITLE
Visibility of various different slack channels

### ISSUE THREAD

**Issue by bharitwal** [WomenWhoCode/WWCode-London#10]
As a part of the volunteer feedback for 'mock-behavioral-interview' project below feedback was received:

`In general, we need to work on visiblity of various channels, also if we could have in-person meetup sometime soon. It will be a boost to the community.`

**Comment by irenkamalova** [comment]
I created a message with all our channels and updating it in #general channel.
Right now, the welcoming bot also send this channel.
I've seen thankful reactions, hence we can close this issue.
