### ISSUE TITLE
Social Media Visibility 

### ISSUE THREAD

**Issue by bharitwal** [WomenWhoCode/WWCode-London#11]
As a part of the volunteer feedback for 'mock-behavioral-interview' project below feedback was received:

`Social media`

I am interpreting this to be more visibility across social media.

**Comment by irenkamalova** [comment]
@nora-weisser created linkree with all resources https://linktr.ee/wwcode_london and we're publishing it everywhere.
We didn't receive the same feedback, hence I'm closing the issue.
