### ISSUE TITLE
Add an automated welcome message for new members

### ISSUE THREAD

**Issue by bharitwal** [WomenWhoCode/WWCode-London#14]

**Comment by irenkamalova** [comment]
I've created two bots for automatic replies:

1. The one reacts to the phrase 'Welcome to WWCODE London!'
It sends a message with navigation in our channel.
2. The one reacts to the phrase 'Thank you for applying as a volunteer!'
It sends a message with volunteering opportunities: which person to reach for advising their help.

You can use these phrases to welcome new members in #welcome and share volunteering opportunities in #i_want_to_help channel!
