### ISSUE TITLE
Create a folder for BookClub and a list of previously discussed books.

### ISSUE THREAD

**Issue by irenkamalova** [WomenWhoCode/WWCode-London#27]

**Comment by irenkamalova** [comment]
[The Grit Factor](https://www.meetup.com/Women-Who-Code-London/events/279004066/)
[Radical Candor](https://www.meetup.com/Women-Who-Code-London/events/280377784/)
[Crucial Conversations](https://www.meetup.com/Women-Who-Code-London/events/284608280/)
[The Culture Map by Erin Meyer](https://www.meetup.com/Women-Who-Code-London/events/285797115/)
[Quiet by Susan Cain](https://www.meetup.com/women-who-code-london/events/286717280/)
[The Myth of the Nice Girl](https://www.meetup.com/women-who-code-london/events/288385153/)

For the first event,  The Grit Factor, the outcome is here: https://iren-kamalova.medium.com/grit-factor-cc597dbf107f

**Comment by irenkamalova** [comment]
Create a resource in section 'resources' for 'book-club'
The best way to represent it in the table:

<book cover / picture with book > | <book name & author >  | Description | Outcome - blogpost |

**Comment by j4sum** [comment]
Will fix soon. Thanks

**Comment by irenkamalova** [comment]
Done! ✅
