### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by antra0497** [WomenWhoCode/WWCode-London#7]
Hi moderators,

The link mentioned for Book Club and Volunteering Summit are incorrect and they are being directed to some ML Azure ppt. 
![image](https://user-images.githubusercontent.com/25953832/190686958-5280494e-fee6-4b60-a4bf-7af41da39a3f.png)

If possible kindly updated the links
Thanks

**Comment by bharitwal** [comment]
Thanks @antra0497 . 

PR https://github.com/WomenWhoCode/WWCode-London/pull/6 addresses this.

**Comment by dricazenck** [comment]
We can close this issue, the doc changes was merged.
