### ISSUE TITLE
Welcome new people within the community 

### ISSUE THREAD

**Issue by bharitwal** [WomenWhoCode/WWCode-London#9]
As a part of the volunteer feedback for 'mock-behavioral-interview' project below feedback was received: 

`Welcoming new people more intentionally. At personal level as well as sending every new person some sort of form to help exploring their skill set and needs.`

- [x] #14 
- [x] #20

**Comment by dricazenck** [comment]
@irenkamalova I guess we can close this issue right?

**Comment by irenkamalova** [comment]
Yes! Thank you!
